---
language: python
python: 2.7
cache: pip
sudo: required

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - pip install -U -r test-requirements.txt

install:
  - "./scripts/install.sh"

before script:
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"
