---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fault-injection
spec:
  hosts:
    - cloudant-service.default.svc.cluster.local
  http:
    - fault:
        delay:
          percent: 100
          fixedDelay: 1.1s
      route:
        - destination:
            host: cloudant-service.default.svc.cluster.local
